server:
  port: 8099
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .

# User Define
app:
  imgdir: file:/root/uimg
  logdir: file:/root/logs