server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
logging:
  level:
    root: info

# ?? ??(?? ??) ?? ?? ?? ??
#  logging.level.root=info
# ????? ?? ?? ?? ?
# logging.level.gd.fintech.webapp=info
# logging.level.gd.fintech.webapp.controller=debug
# logging.level.gd.fintech.webapp.mapper=trace


# User Define
app:
  imgdir: file:///c:/project/uimg
  logdir: file:///c:/project/logs